/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { OrderUpdateManyWithoutFarmersInput } from "./OrderUpdateManyWithoutFarmersInput";
import { Type } from "class-transformer";
import { ProfileUpdateManyWithoutFarmersInput } from "./ProfileUpdateManyWithoutFarmersInput";
import { SalesUpdateManyWithoutFarmersInput } from "./SalesUpdateManyWithoutFarmersInput";

@InputType()
class FarmerUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => OrderUpdateManyWithoutFarmersInput,
  })
  @ValidateNested()
  @Type(() => OrderUpdateManyWithoutFarmersInput)
  @IsOptional()
  @Field(() => OrderUpdateManyWithoutFarmersInput, {
    nullable: true,
  })
  orders?: OrderUpdateManyWithoutFarmersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProfileUpdateManyWithoutFarmersInput,
  })
  @ValidateNested()
  @Type(() => ProfileUpdateManyWithoutFarmersInput)
  @IsOptional()
  @Field(() => ProfileUpdateManyWithoutFarmersInput, {
    nullable: true,
  })
  profiles?: ProfileUpdateManyWithoutFarmersInput;

  @ApiProperty({
    required: false,
    type: () => SalesUpdateManyWithoutFarmersInput,
  })
  @ValidateNested()
  @Type(() => SalesUpdateManyWithoutFarmersInput)
  @IsOptional()
  @Field(() => SalesUpdateManyWithoutFarmersInput, {
    nullable: true,
  })
  salesItems?: SalesUpdateManyWithoutFarmersInput;
}

export { FarmerUpdateInput as FarmerUpdateInput };
