/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CropService } from "../crop.service";
import { CropCreateInput } from "./CropCreateInput";
import { Crop } from "./Crop";
import { CropFindManyArgs } from "./CropFindManyArgs";
import { CropWhereUniqueInput } from "./CropWhereUniqueInput";
import { CropUpdateInput } from "./CropUpdateInput";

export class CropControllerBase {
  constructor(protected readonly service: CropService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Crop })
  async createCrop(@common.Body() data: CropCreateInput): Promise<Crop> {
    return await this.service.createCrop({
      data: data,
      select: {
        createdAt: true,
        harvestDate: true,
        id: true,
        name: true,
        plantingDate: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Crop] })
  @ApiNestedQuery(CropFindManyArgs)
  async crops(@common.Req() request: Request): Promise<Crop[]> {
    const args = plainToClass(CropFindManyArgs, request.query);
    return this.service.crops({
      ...args,
      select: {
        createdAt: true,
        harvestDate: true,
        id: true,
        name: true,
        plantingDate: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Crop })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async crop(
    @common.Param() params: CropWhereUniqueInput
  ): Promise<Crop | null> {
    const result = await this.service.crop({
      where: params,
      select: {
        createdAt: true,
        harvestDate: true,
        id: true,
        name: true,
        plantingDate: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Crop })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCrop(
    @common.Param() params: CropWhereUniqueInput,
    @common.Body() data: CropUpdateInput
  ): Promise<Crop | null> {
    try {
      return await this.service.updateCrop({
        where: params,
        data: data,
        select: {
          createdAt: true,
          harvestDate: true,
          id: true,
          name: true,
          plantingDate: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Crop })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCrop(
    @common.Param() params: CropWhereUniqueInput
  ): Promise<Crop | null> {
    try {
      return await this.service.deleteCrop({
        where: params,
        select: {
          createdAt: true,
          harvestDate: true,
          id: true,
          name: true,
          plantingDate: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
